#!/bin/bash

shopt -s extglob # enable pattern matching for 'case'

err=0

# won't process these options
excludes="+(--no-quiet|--html-extension)"

for opt in `src/wget2 --help|egrep -o -- '--[a-zA-Z0-9-]+'|sort -u`; do
  # skip if in $excludes
  case $opt in $excludes) continue;; esac

  if ! egrep -q -- " \`$opt(=|\`|\[)" $1; then
    # search for the --no- variant
    noopt="--no-`echo $opt|cut -c3-`"
    if ! egrep -q -- " \`$noopt\`" $1; then
      echo "Failed to find \`$opt in $1"
      err=1
    fi
  fi
done

exit $err
