#!/usr/bin/env python

import sys
import csv
import json

if __name__=="__main__":
  reader = csv.DictReader(sys.stdin)
  output = json.dumps([r for r in reader], sort_keys=False, indent=4, separators=(',', ': '))
  sys.stdout.write(output)
