#!/usr/bin/env sh
#
# see https://github.com/codespell-project/codespell
#
# in short:
#  - pip install codespell
#  - add ~/.local/bin to PATH

codespell $* -L "tim,gonna,cas,referer,fpr" `git ls-files|\
  egrep -v '_fuzzer.in|_fuzzer.repro|\.der$|\.pem$|gnulib|ChangeLog|tests/gpg|\.png$|\.dat$|src/wget.c|contrib/spell-checker'`

codespell $* -L "tim,gonna,cas,te,referer,ist,fpr" src/wget.c contrib/spell-checker
