/*
 * Copyright(c) 2014 Tim Ruehsen
 *
 * This file is part of libmget.
 *
 * Libmget is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Libmget is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with libmget.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * OCSP routines
 *
 * Changelog
 * 08.01.2015  Tim Ruehsen  created
 *
 */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <errno.h>

#include <libmget.h>
#include "private.h"

struct _mget_ocsp_db_st {
	mget_hashmap_t *
		entries;
	mget_thread_mutex_t
		mutex;
};

struct _mget_ocsp_st {
	const char *
		host;
	time_t
		maxage; // expiry time
	time_t
		mtime; // creation time
};

static unsigned int G_GNUC_MGET_PURE _hash_ocsp(const mget_ocsp_t *ocsp)
{
	unsigned int hash = 0;
	const unsigned char *p;

	for (p = (unsigned char *)ocsp->host; *p; p++)
		hash = hash * 101 + *p;

	return hash;
}

static int G_GNUC_MGET_NONNULL_ALL _compare_ocsp(const mget_ocsp_t *h1, const mget_ocsp_t *h2)
{
	return strcmp(h1->host, h2->host);
}

mget_ocsp_t *mget_ocsp_init(mget_ocsp_t *ocsp)
{
	if (!ocsp)
		ocsp = xmalloc(sizeof(mget_ocsp_t));

	memset(ocsp, 0, sizeof(*ocsp));
	ocsp->mtime = time(NULL);

	return ocsp;
}

void mget_ocsp_deinit(mget_ocsp_t *ocsp)
{
	if (ocsp) {
		xfree(ocsp->host);
	}
}

void mget_ocsp_free(mget_ocsp_t **ocsp)
{
	if (ocsp) {
		mget_ocsp_deinit(*ocsp);
		xfree(*ocsp);
	}
}

mget_ocsp_t *mget_ocsp_new(const char *host, time_t maxage)
{
	mget_ocsp_t *ocsp = mget_ocsp_init(NULL);

	ocsp->host = mget_strdup(host);
	ocsp->maxage = maxage;

	return ocsp;
}

int mget_ocsp_is_valid(const mget_ocsp_db_t *ocsp_db, const char *host)
{
	if (ocsp_db) {
		mget_ocsp_t ocsp, *ocspp;

		// look for an exact match
		ocsp.host = host;
		if ((ocspp = mget_hashmap_get(ocsp_db->entries, &ocsp)) && ocspp->maxage >= time(NULL))
			return 1;
	}

	return 0;
}

mget_ocsp_db_t *mget_ocsp_db_init(mget_ocsp_db_t *ocsp_db)
{
	if (!ocsp_db)
		ocsp_db = xmalloc(sizeof(mget_ocsp_db_t));

	memset(ocsp_db, 0, sizeof(*ocsp_db));
	ocsp_db->entries = mget_hashmap_create(16, -2, (unsigned int(*)(const void *))_hash_ocsp, (int(*)(const void *, const void *))_compare_ocsp);
	mget_hashmap_set_destructor(ocsp_db->entries, (void(*)(void *, void *))mget_ocsp_deinit);
	mget_thread_mutex_init(&ocsp_db->mutex);

	return ocsp_db;
}

void mget_ocsp_db_deinit(mget_ocsp_db_t *ocsp_db)
{
	if (ocsp_db) {
		mget_thread_mutex_lock(&ocsp_db->mutex);
		mget_hashmap_free(&ocsp_db->entries);
		mget_thread_mutex_unlock(&ocsp_db->mutex);
	}
}

void mget_ocsp_db_free(mget_ocsp_db_t **ocsp_db)
{
	if (ocsp_db) {
		mget_ocsp_db_deinit(*ocsp_db);
		xfree(*ocsp_db);
	}
}

void mget_ocsp_db_add(mget_ocsp_db_t *ocsp_db, mget_ocsp_t *ocsp)
{
	mget_thread_mutex_lock(&ocsp_db->mutex);

	if (ocsp->maxage == 0) {
		if (mget_hashmap_remove(ocsp_db->entries, ocsp))
			debug_printf("removed OCSP %s\n", ocsp->host);
		mget_ocsp_free(&ocsp);
	} else {
		mget_ocsp_t *old = mget_hashmap_get(ocsp_db->entries, ocsp);

		if (old) {
			if (old->mtime < ocsp->mtime) {
				old->mtime = ocsp->mtime;
				old->maxage = ocsp->maxage;
				debug_printf("update OCSP %s (maxage=%ld)\n", old->host, old->maxage);
			}
			mget_ocsp_free(&ocsp);
		} else {
			// key and value are the same to make mget_hashmap_get() return old 'ocsp'
			mget_hashmap_put_noalloc(ocsp_db->entries, ocsp, ocsp);
			debug_printf("stored OCSP %s (maxage=%ld)\n", ocsp->host, ocsp->maxage);
			// no need to free anything here
		}
	}

	mget_thread_mutex_unlock(&ocsp_db->mutex);
}

static int G_GNUC_MGET_NONNULL_ALL _ocsp_save(FILE *fp, const mget_ocsp_t *ocsp)
{
	fprintf(fp, "%s %ld %ld\n", ocsp->host, ocsp->maxage, ocsp->mtime);
	return 0;
}

// save the OCSP cache to a flat file
// not thread-save

int mget_ocsp_db_save(mget_ocsp_db_t *ocsp_db, const char *fname)
{
	FILE *fp;
	int ret = -1, size;

	if (!fname || !*fname)
		return -1;

	mget_ocsp_db_load(ocsp_db, fname);

	if ((size = mget_hashmap_size(ocsp_db->entries)) <= 0)
		return -1;

	if ((fp = fopen(fname, "w"))) {
		fputs("#OCSP 1.0 file\n", fp);
		fputs("#Generated by Mget " PACKAGE_VERSION ". Edit at your own risk.\n\n", fp);

		mget_hashmap_browse(ocsp_db->entries, (int(*)(void *, const void *, void *))_ocsp_save, fp);

		if (!ferror(fp))
			ret = 0;

		if (fclose(fp))
			ret = -1;

		if (ret)
			error_printf(_("Failed to write to OCSP file '%s' (%d)\n"), fname, errno);
		else
			debug_printf(_("saved %d OCSP entr%s into '%s'\n"), size, size != 1 ? "ies" : "y", fname);
	} else
		error_printf(_("Failed to open OCSP file '%s' (%d)\n"), fname, errno);

	return ret;
}

// load the OCSP cache from a flat file
// not thread-save

int mget_ocsp_db_load(mget_ocsp_db_t *ocsp_db, const char *fname)
{
	mget_ocsp_t ocsp;
	FILE *fp;
	char *buf = NULL, *linep, *p;
	size_t bufsize = 0;
	ssize_t buflen;
	time_t now = time(NULL);
	int ok, nentries = 0;

	if (!ocsp_db || !fname || !*fname)
		return 0;

	if ((fp = fopen(fname, "r"))) {
		while ((buflen = mget_getline(&buf, &bufsize, fp)) >= 0) {
			linep = buf;

			while (isspace(*linep)) linep++; // ignore leading whitespace
			if (!*linep) continue; // skip empty lines

			if (*linep == '#')
				continue; // skip comments

			// strip off \r\n
			while (buflen > 0 && (buf[buflen] == '\n' || buf[buflen] == '\r'))
				buf[--buflen] = 0;

			mget_ocsp_init(&ocsp);
			ok = 0;

			// parse host
			if (*linep) {
				for (p = linep; *linep && !isspace(*linep);) linep++;
				ocsp.host = strndup(p, linep - p);
			}

			// parse max age
			if (*linep) {
				for (p = ++linep; *linep && !isspace(*linep);) linep++;
				ocsp.maxage = atol(p);
				if (ocsp.maxage < now) {
					// drop expired entry
					mget_ocsp_deinit(&ocsp);
					continue;
				}
				ok = 1;
			}

			// parse mtime (age of this entry)
			if (*linep) {
				for (p = ++linep; *linep && !isspace(*linep);) linep++;
				ocsp.mtime = atol(p);
			}

			if (ok) {
				mget_ocsp_db_add(ocsp_db, mget_memdup(&ocsp, sizeof(ocsp)));
			} else {
				mget_ocsp_deinit(&ocsp);
				error_printf(_("Failed to parse OCSP line: '%s'\n"), buf);
			}
		}

		xfree(buf);
		fclose(fp);

		nentries = mget_hashmap_size(ocsp_db->entries);

		debug_printf(_("have %d OCSP entr%s in cache\n"), nentries, nentries !=1 ? "ies" : "y");
	} else if (errno != ENOENT)
		error_printf(_("Failed to open OCSP file '%s' (%d)\n"), fname, errno);

	return nentries;
}
